version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER:
      POSTGRES_PASSWORD: 
    volumes:
      - postgres:/var/lib/postgresql/data
  web:
    env_file: .env
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/url-shortener
    ports:
      - "3000:3000"
    depends_on:
      - db
volumes:
  postgres: