version: '3'
services:
 db:
  image: postgres
  environment:
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: secretP@wd
  volumes:
   - ./tmp/db:/var/lib/postgresql/data
 web:
  build: .
  command: bundle exec rails s -p 3000 -b '0.0.0.0'
  volumes:
   - .:/shortener-app
  ports:
   - "3000:3000"
  depends_on:
   - db
